### ISSUE TITLE
Using SDK with MC60 module

### ISSUE THREAD

**Issue by chandankumar1** [waybyte/logicromsdk#2]
I tried compiling a simple program for MC60 and upload the bin file. But after that I am not able to use GPS in eclipse SDK. I had flashed MC60 with latest core firmware but it does not work. I tried with/without application but problem remains same.

https://forums.quectel.com/t/unable-to-use-gps-in-application-in-mc60/10869

**Comment by ajaybhargav** [comment]
I am not sure if this question is relevant to LogicromSDK. I believe it has more to do with your hardware and sdk/code you're using. I have gone through the thread and probably you need to follow instructions given by the Quectel FAE.
