### ISSUE TITLE
Arduino CRC package problem

### ISSUE THREAD

**Issue by dougalvesreis** [waybyte/logicromsdk#3]
CRC não corresponde, o arquivo está corrompido. Pode ser um problema temporário, tente novamente mais tarde.
java.lang.RuntimeException: java.lang.Exception: CRC não corresponde, o arquivo está corrompido. Pode ser um problema temporário, tente novamente mais tarde.
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:179)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: CRC não corresponde, o arquivo está corrompido. Pode ser um problema temporário, tente novamente mais tarde.
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:105)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:60)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:112)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more

**Comment by ajaybhargav** [comment]
Are you using Arduino IDE or PlatformIO?

**Comment by dougalvesreis** [comment]
Hello! Using Arduino.

Em qua., 6 de out. de 2021 11:13, Ajay Bhargav ***@***.***>
escreveu:

**Comment by ajaybhargav** [comment]
That's unfortunate. I have just released a new version for Arduino with LTE support. You can give that a try. Remove any old installation just in case and install v0.6.0. Let me know if you still see any issue.

**Comment by dsptech** [comment]
Hi, this issue is still on. Any news ?

**Comment by ajaybhargav** [comment]
Not anymore. I mean it's fixed

**Comment by dsptech** [comment]
@ajaybhargav, please see the referencing issue.

**Comment by dougalvesreis** [comment]
Use platformio instead. Worked fine.

Em sáb., 25 de dez. de 2021 11:51, dsptech ***@***.***>
escreveu:

**Comment by ajaybhargav** [comment]
@dougalvesreis I have fixed the issue now with Arduino IDE. It was due to toolchain not getting downloaded from GitHub server. I changed the server now. Thanks!

**Comment by dsptech** [comment]
Hi @ajaybhargav,
the link inside https://waybyte.github.io/package_logicrom_index.json (https://waybyte.github.io/gcc-arm-none-eabi-8-2018-q4.tar.gz) still has the issue. 
Regards.

**Comment by ajaybhargav** [comment]
hi @dsptech that's just a bad luck. GitHub deployment failed, Just redeployed it and its up now. You may check.

**Comment by dsptech** [comment]
Hi @ajaybhargav,
Confirmed!. Now, the link inside the json is: https://waybyte.in/toolchain/gcc-arm-none-eabi-8-2018-q4.tar.gz
Thank you.
Regards.

**Comment by sinaaa99** [comment]
> Hi @ajaybhargav, Confirmed!. Now, the link inside the json is: https://waybyte.in/toolchain/gcc-arm-none-eabi-8-2018-q4.tar.gz Thank you. Regards.

hi
i did not get the point
when i install logicRom Arduino i get this eror "error downloading https://waybyte.in/toolchain/gcc-arm-none-eabi-8-2018-q4.tar.gz"
and stop installingو What should I do?

**Comment by dsptech** [comment]
Hi, it seems that the toolchain has been removed from the waybyte.in website (http error 404). This is a question for @ajaybhargav.
Regards

**Comment by ajaybhargav** [comment]
@dsptech Thanks. I fixed it. I recently moved my server and file was lost.
