### ISSUE TITLE
problem with A9 GSM/GPRS Module and Arduino

### ISSUE THREAD

**Issue by behi88** [waybyte/logicromsdk#4]
Hi 
I try to use A9 (RDA8955) Module with Arduino and Logicrom in VScode PlatformIO.
but the Firmware. Lod File is so small after the compiling (about 270kB)
any way I burn the  the file in to the a( flash with CoolTrace program and It did not work.
for testing I try to compile a Blinky program with GPRS_C_SDK and it just work out of the box so there is no problem with Hardware
please advise

**Comment by ajaybhargav** [comment]
Arduino support is not yet complete for RDA8955, but Logicrom is fully supported.
I hope you have activated your device to use Logicrom, if not Please follow this:
https://github.com/waybyte/platform-logicrom#get-free-personal-license

**Comment by ajaybhargav** [comment]
Please also make sure you use following core firmware with Logicrom:
https://github.com/waybyte/logicrom_core/tree/master/2G_RDA8955

**Comment by behi88** [comment]
it works!
I did not activate my device.
thank you.
